// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pirzzriipazqvybspclm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpcnp6cmlpcGF6cXZ5YnNwY2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NDIyMjIsImV4cCI6MjA2OTAxODIyMn0.cG5IeJS3YqnmByTvdOY5H64Op0jPc80aopdpDLWxLg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});